version: '3.9'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    environment:
      FLASK_ENV: development  # Für Entwicklungszwecke
    volumes:
      - .:/app  # Binde den lokalen Code in den Container
    #restart: unless-stopped
