name: Release from tag

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Publish release
      id: publish-release
      uses: ghalactic/github-release-from-tag@v5
      with:
         prerelease: "false"
         reactions: heart,rocket,eyes

  executable:
    runs-on: windows-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.11'
        spec: 'main.spec'
        requirements: 'requirements.txt'
        upload_exe_with_name: 'zu-bbbearbeiten.exe'

    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        gh release upload ${{ github.ref_name }} ./dist/main.exe
