name: Release from tag

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: set lower case owner name
      id: lowercase_username
      run: |
        echo "actor=${OWNER,,}" >> $GITHUB_OUTPUT
      env:
        OWNER: '${{ github.repository_owner }}'
      shell: bash

    - name: Build the Docker container
      run: |
            docker build . --tag ghcr.io/${{ steps.lowercase_username.outputs.actor }}/${{ github.event.repository.name }}:latest
            docker push ghcr.io/${{ steps.lowercase_username.outputs.actor }}/${{ github.event.repository.name }}:latest
